name: Test and Deploy prom-app

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch
  pull_request:
    branches:
      - main  # Trigger the workflow on pull requests to the main branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image with Datadog build args
      run: |
        # Get Git repository URL and commit SHA
        REPO_URL=$(git config --get remote.origin.url)
        COMMIT_SHA=$(git rev-parse HEAD)
        
        # Build Docker image with build arguments
        docker build . \
          -t ${{ secrets.DOCKER_USERNAME }}/prom-app:latest \
          --build-arg DD_GIT_REPOSITORY_URL=${REPO_URL} \
          --build-arg DD_GIT_COMMIT_SHA=${COMMIT_SHA}

    - name: Push Docker image
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/prom-app:latest